Repository PASTA-ELN/pasta-eln, pull requests merged in 2023-10, with the labels that each got.

#71 repaired issue #64
  pasta_eln/GUI/form.py
Labels: bug

#70 fixed issue #65
  pasta_eln/gui.py
Labels: bug

#72 repaired #59
  pasta_eln/GUI/tableHeader.py
Labels: bug

#75 feat(ontology): auto-populating IRI fields of ontology editor tool
  .github/workflows/pytest.yml
  .pylintrc
  pasta_eln/GUI/ontology_configuration/create_type_dialog.py
  pasta_eln/GUI/ontology_configuration/create_type_dialog.ui
  pasta_eln/GUI/ontology_configuration/create_type_dialog_extended.py
  pasta_eln/GUI/ontology_configuration/delete_column_delegate.py
  pasta_eln/GUI/ontology_configuration/iri_column_delegate.py
  pasta_eln/GUI/ontology_configuration/lookup_iri_action.py
  pasta_eln/GUI/ontology_configuration/ontology_attachments_tableview_data_model.py
  pasta_eln/GUI/ontology_configuration/ontology_config_generic_exception.py
  pasta_eln/GUI/ontology_configuration/ontology_config_key_not_found_exception.py
  pasta_eln/GUI/ontology_configuration/ontology_configuration.py
  pasta_eln/GUI/ontology_configuration/ontology_configuration.ui
  pasta_eln/GUI/ontology_configuration/ontology_configuration_constants.py
  pasta_eln/GUI/ontology_configuration/ontology_configuration_extended.py
  pasta_eln/GUI/ontology_configuration/ontology_document_null_exception.py
  pasta_eln/GUI/ontology_configuration/ontology_props_tableview_data_model.py
  pasta_eln/GUI/ontology_configuration/ontology_tableview_data_model.py
  pasta_eln/GUI/ontology_configuration/reorder_column_delegate.py
  pasta_eln/GUI/ontology_configuration/required_column_delegate.py
  pasta_eln/GUI/ontology_configuration/terminology_lookup_config.json
  pasta_eln/GUI/ontology_configuration/terminology_lookup_dialog.py
  pasta_eln/GUI/ontology_configuration/terminology_lookup_dialog_base.py
  pasta_eln/GUI/ontology_configuration/terminology_lookup_dialog_base.ui
  pasta_eln/GUI/ontology_configuration/terminology_lookup_service.py
  pasta_eln/GUI/ontology_configuration/utility_functions.py
  pasta_eln/Resources/Icons/ols.png
  pasta_eln/Resources/Icons/tib.png
  pasta_eln/Resources/Icons/wikidata.png
  pasta_eln/Resources/Icons/wikipedia.png
  requirements-linux.txt
  requirements-windows.txt
  setup.cfg
  tests/app_tests/common/fixtures.py
  tests/app_tests/common/test_utils.py
  tests/app_tests/component_tests/test_ontology_configuration_extended.py
  tests/app_tests/test_data/iri_lookup_web_results_name.json
  tests/app_tests/test_data/iri_lookup_web_results_pasta.json
  tests/app_tests/test_data/iri_lookup_web_results_science.json
  tests/app_tests/test_data/retrieved_iri_results_name.json
  tests/app_tests/test_data/retrieved_iri_results_pasta.json
  tests/app_tests/test_data/retrieved_iri_results_science.json
  tests/app_tests/unit_tests/test_ontology_config_configuration_extended.py
  tests/app_tests/unit_tests/test_ontology_config_create_type_dialog_extended.py
  tests/app_tests/unit_tests/test_ontology_config_delete_column_delegate.py
  tests/app_tests/unit_tests/test_ontology_config_document_null_exception.py
  tests/app_tests/unit_tests/test_ontology_config_iri_column_delegate.py
  tests/app_tests/unit_tests/test_ontology_config_key_not_found_exception.py
  tests/app_tests/unit_tests/test_ontology_config_lookup_iri_action.py
  tests/app_tests/unit_tests/test_ontology_config_reorder_column_delegate.py
  tests/app_tests/unit_tests/test_ontology_config_required_column_delegate.py
  tests/app_tests/unit_tests/test_ontology_config_table_view_data_model.py
  tests/app_tests/unit_tests/test_ontology_config_terminology_lookup_dialog.py
  tests/app_tests/unit_tests/test_ontology_config_terminology_lookup_service.py
  tests/app_tests/unit_tests/test_ontology_config_utility_functions.py
Labels: enhancement

#80 fix(ontology): introduced check for properties with empty names
  pasta_eln/GUI/ontology_configuration/ontology_configuration_extended.py
  pasta_eln/GUI/ontology_configuration/utility_functions.py
  tests/app_tests/unit_tests/test_ontology_config_configuration_extended.py
  tests/app_tests/unit_tests/test_ontology_config_utility_functions.py
Labels: bug

#77 fix(ontology): enabled auto stretch for the property table
  pasta_eln/GUI/ontology_configuration/ontology_configuration_extended.py
Labels: bug

#74 repaired #36 #20
  pasta_eln/GUI/form.py
  pasta_eln/GUI/project.py
Labels: bug

#83 fix(ontology): deletion of structural level types & normal types
  pasta_eln/GUI/ontology_configuration/ontology_configuration_extended.py
  pasta_eln/GUI/ontology_configuration/utility_functions.py
  tests/app_tests/common/fixtures.py
  tests/app_tests/component_tests/test_ontology_configuration_extended.py
  tests/app_tests/unit_tests/test_ontology_config_configuration_extended.py
  tests/app_tests/unit_tests/test_ontology_config_utility_functions.py
Labels: bug, enhancement

#100 test(ontology): added automated tests for ontology component
  pasta_eln/GUI/ontology_configuration/ontology_configuration_extended.py
  tests/app_tests/component_tests/test_ontology_configuration_extended.py
  tests/app_tests/unit_tests/test_ontology_config_configuration_extended.py
Labels: enhancement

#101 fix(ontology): consecutive save click throws console errors
  pasta_eln/GUI/ontology_configuration/ontology_configuration_extended.py
  pasta_eln/GUI/ontology_configuration/utility_functions.py
  tests/app_tests/component_tests/test_ontology_configuration_extended.py
  tests/app_tests/unit_tests/test_ontology_config_configuration_extended.py
  tests/app_tests/unit_tests/test_ontology_config_utility_functions.py
Labels: bug

#102 fix(ontology): runtime errors been thrown for flags returning NoneType
  pasta_eln/GUI/ontology_configuration/ontology_tableview_data_model.py
  tests/app_tests/component_tests/test_ontology_configuration_extended.py
  tests/app_tests/unit_tests/test_ontology_config_table_view_data_model.py
Labels: bug

#73 repaired issue #63
  pasta_eln/GUI/_contextMenu.py
  pasta_eln/GUI/form.py
  pasta_eln/GUI/project.py
  pasta_eln/GUI/projectTreeView.py
  pasta_eln/database.py
Labels: bug
