Repository PASTA-ELN/pasta-eln, pull requests merged in 2023-09, with the labels that each got.

#23 feat(ontology): added tests for the ontology editor
  .pylintrc
  pasta_eln/GUI/ontology_configuration/__init__.py
  pasta_eln/GUI/ontology_configuration/create_type_dialog.py
  pasta_eln/GUI/ontology_configuration/create_type_dialog.ui
  pasta_eln/GUI/ontology_configuration/create_type_dialog_extended.py
  pasta_eln/GUI/ontology_configuration/delete_column_delegate.py
  pasta_eln/GUI/ontology_configuration/ontology_attachments_tableview_data_model.py
  pasta_eln/GUI/ontology_configuration/ontology_config_generic_exception.py
  pasta_eln/GUI/ontology_configuration/ontology_config_key_not_found_exception.py
  pasta_eln/GUI/ontology_configuration/ontology_configuration.py
  pasta_eln/GUI/ontology_configuration/ontology_configuration.ui
  pasta_eln/GUI/ontology_configuration/ontology_configuration_constants.py
  pasta_eln/GUI/ontology_configuration/ontology_configuration_extended.py
  pasta_eln/GUI/ontology_configuration/ontology_document_null_exception.py
  pasta_eln/GUI/ontology_configuration/ontology_props_tableview_data_model.py
  pasta_eln/GUI/ontology_configuration/ontology_tableview_data_model.py
  pasta_eln/GUI/ontology_configuration/reorder_column_delegate.py
  pasta_eln/GUI/ontology_configuration/required_column_delegate.py
  pasta_eln/GUI/ontology_configuration/utility_functions.py
  pasta_eln/database.py
  pasta_eln/gui.py
  run_tests.sh
  setup.cfg
  tests/__init__.py
  tests/app_tests/__init__.py
  tests/app_tests/common/__init__.py
  tests/app_tests/common/fixtures.py
  tests/app_tests/common/test_delegate_funcs_common.py
  tests/app_tests/common/test_utils.py
  tests/app_tests/component_tests/__init__.py
  tests/app_tests/component_tests/test_ontology_configuration_extended.py
  tests/app_tests/integration/__init__.py
  tests/app_tests/integration/test_pasta_app_ui.py
  tests/app_tests/test_data/__init__.py
  tests/app_tests/test_data/ontology_document.json
  tests/app_tests/unit_tests/__init__.py
  tests/app_tests/unit_tests/test_ontology_config_configuration_extended.py
  tests/app_tests/unit_tests/test_ontology_config_create_type_dialog_extended.py
  tests/app_tests/unit_tests/test_ontology_config_delete_column_delegate.py
  tests/app_tests/unit_tests/test_ontology_config_document_null_exception.py
  tests/app_tests/unit_tests/test_ontology_config_key_not_found_exception.py
  tests/app_tests/unit_tests/test_ontology_config_reorder_column_delegate.py
  tests/app_tests/unit_tests/test_ontology_config_required_column_delegate.py
  tests/app_tests/unit_tests/test_ontology_config_table_view_data_model.py
  tests/app_tests/unit_tests/test_ontology_config_utility_functions.py
  tests/test_99_3Projects.py
Labels: enhancement

#27 ci(ontology): added pytest and coverage calculation as a workflow
  .github/workflows/pytest.yml
  requirements-linux.txt
  requirements-windows.txt
  tests/test_01_demoIndentation.py
  tests/test_02_demoIndentation_ExportImport.py
  tests/test_99_3Projects.py
Labels: enhancement

#29 Reformat gui.py to allow for easier reading
  pasta_eln/gui.py
Labels: enhancement

#22 Content of form is autosaved in home folder. If computer is closed wi…
  pasta_eln/GUI/form.py
  pasta_eln/gui.py
Labels: Priority 1: small

#39 Implement new version 3 of the ontology into the backend.
  pasta_eln/GUI/details.py
  pasta_eln/GUI/form.py
  pasta_eln/GUI/ontology.py
  pasta_eln/GUI/ontology_configuration/utility_functions.py
  pasta_eln/GUI/tableHeader.py
  pasta_eln/database.py
  pasta_eln/fixedStringsJson.py
  pasta_eln/handleDictionaries.py
  pasta_eln/mixin_cli.py
  tests/app_tests/unit_tests/test_ontology_config_utility_functions.py
Labels: bug, Priority 2: important

#46 feat(ontology): editor GUI changes and other modifications
  pasta_eln/GUI/ontology_configuration/create_type_dialog.py
  pasta_eln/GUI/ontology_configuration/create_type_dialog.ui
  pasta_eln/GUI/ontology_configuration/create_type_dialog_extended.py
  pasta_eln/GUI/ontology_configuration/ontology_attachments_tableview_data_model.py
  pasta_eln/GUI/ontology_configuration/ontology_configuration.py
  pasta_eln/GUI/ontology_configuration/ontology_configuration.ui
  pasta_eln/GUI/ontology_configuration/ontology_configuration_constants.py
  pasta_eln/GUI/ontology_configuration/ontology_configuration_extended.py
  pasta_eln/GUI/ontology_configuration/ontology_props_tableview_data_model.py
  pasta_eln/GUI/ontology_configuration/ontology_tableview_data_model.py
  pasta_eln/GUI/ontology_configuration/required_column_delegate.py
  pasta_eln/GUI/ontology_configuration/utility_functions.py
  pasta_eln/fixedStringsJson.py
  tests/app_tests/common/fixtures.py
  tests/app_tests/component_tests/test_ontology_configuration_extended.py
  tests/app_tests/test_data/ontology_document.json
  tests/app_tests/unit_tests/test_ontology_config_configuration_extended.py
  tests/app_tests/unit_tests/test_ontology_config_create_type_dialog_extended.py
  tests/app_tests/unit_tests/test_ontology_config_required_column_delegate.py
  tests/app_tests/unit_tests/test_ontology_config_table_view_data_model.py
Labels: enhancement, good first issue

#43 change button text-color; tab in textEdit for form
  pasta_eln/GUI/form.py
  pasta_eln/guiStyle.py
Labels: enhancement

#45 Issue 34 debug
  docs/source/conf.py
  pasta_eln/Extractors/extractor_jpeg.py
  pasta_eln/Extractors/extractor_json.py
  pasta_eln/Extractors/extractor_md.py
  pasta_eln/Extractors/extractor_png.py
  pasta_eln/GUI/_contextMenu.py
  pasta_eln/GUI/details.py
  pasta_eln/GUI/form.py
  pasta_eln/GUI/project.py
  pasta_eln/GUI/projectTreeView.py
  pasta_eln/GUI/table.py
  pasta_eln/__init__.py
  pasta_eln/guiStyle.py
  releaseVersion.py
  setup.py
  tests/conftest.py
Labels: bug

#52 docs(ontology): add help button functionality to ontology editor tool
  docs/source/_static/Ontology_Editor_Manual.odp
  docs/source/_static/Ontology_Editor_Manual.pdf
  docs/source/_static/ontology_editor.png
  docs/source/_static/property_category_combo_box.png
  docs/source/_static/types_combo_box.png
  docs/source/dodonts.rst
  docs/source/extractors.rst
  docs/source/faqs.rst
  docs/source/index.rst
  docs/source/motivation.rst
  docs/source/ontology_configuration.rst
  docs/source/userstory.rst
  pasta_eln/GUI/ontology_configuration/delete_column_delegate.py
  pasta_eln/GUI/ontology_configuration/ontology_configuration.py
  pasta_eln/GUI/ontology_configuration/ontology_configuration.ui
  pasta_eln/GUI/ontology_configuration/ontology_configuration_constants.py
  pasta_eln/GUI/ontology_configuration/ontology_configuration_extended.py
  pasta_eln/GUI/ontology_configuration/ontology_tableview_data_model.py
  pasta_eln/GUI/ontology_configuration/reorder_column_delegate.py
  pasta_eln/GUI/ontology_configuration/utility_functions.py
  pasta_eln/fixedStringsJson.py
  pasta_eln/gui.py
  tests/app_tests/common/fixtures.py
  tests/app_tests/common/test_delegate_funcs_common.py
  tests/app_tests/component_tests/test_ontology_configuration_extended.py
  tests/app_tests/test_data/ontology_document.json
  tests/app_tests/unit_tests/test_ontology_config_configuration_extended.py
  tests/app_tests/unit_tests/test_ontology_config_delete_column_delegate.py
  tests/app_tests/unit_tests/test_ontology_config_reorder_column_delegate.py
  tests/app_tests/unit_tests/test_ontology_config_utility_functions.py
Labels: documentation, enhancement

#54 fix(ontology): added missing initDocTypeViews invoke to save function
  pasta_eln/GUI/ontology_configuration/ontology_configuration_extended.py
  pasta_eln/gui.py
  tests/app_tests/common/fixtures.py
  tests/app_tests/component_tests/test_ontology_configuration_extended.py
  tests/app_tests/unit_tests/test_ontology_config_configuration_extended.py
Labels: bug

#53 safeguard if data-label not present in default set of icons
  pasta_eln/GUI/project.py
  pasta_eln/GUI/sidebar.py
  pasta_eln/database.py
  pasta_eln/gui.py
Labels: bug
